# Generated by Django 4.1.7 on 2023-02-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('agent', models.CharField(max_length=255)),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('create_user_company', models.CharField(max_length=255)),
            ],
        ),
    ]
